draft-ounsworth-csr-attestation.md
[Tweaked intro to (hopefully) line up with RATS terminology](https://github.com/lamps-wg/csr-attestation/commit/4ffe0f026c5f6446bb20cb617e60d2a072c171d8)
=> Mike rats terms

draft-ounsworth-csr-attestation.md
I removed the duplication between the #Introduction and the #Architecture sections.
=> Mike gut intro

draft-ounsworth-csr-attestation.md
Break up some long sentences.
Tweak some 9334 terminology usage.
=> Mcr editorial 01

draft-ietf-lamps-csr-attestation.md
Merging this PR requires closing PR#20
=> Fixed merge conflicts of PR#20 

draft-ietf-lamps-csr-attestation.md
@meyer_chris if you're ok with this, I proposed to merge this PR and close #38 .
=> Extracted meaningful content changes from Chris' PR 38.

CSR-ATTESTATION-2023.asn, CSR-ATTESTATION-WITH-DICE-CMW.asn, draft-ietf-lamps-csr-attestation.md
This PR's not super clean because it's sitting on top of the changes for #42.
The relevant change is this:
https://github.com/lamps-wg/csr-attestation/pull/44/files#diff-9b88f7a24d6eff606780b418b2e2d8ff3e7a400513a2249abd64b87c26686bcf
=> Example of encoding a TCG DICE CMW

draft-ietf-lamps-csr-attestation.md
Rather extensive overhaul. Please check!
=> terminololgy and phrasing in Introduction

draft-ietf-lamps-csr-attestation.md
Addressing https://github.com/lamps-wg/csr-attestation/issues/37
=> Addressing Passport Model

draft-ietf-lamps-csr-attestation.md
Added explanatory text to TCG DICE example.
Also in this PR: I fixed a discrepancy between the ASN.1 module and the copy of the ASN.1 in the body.
=> Mike dice text

CSR-ATTESTATION-2023.asn, draft-ietf-lamps-csr-attestation.md
=> Defined EvidenceBundles to make Russ happy :)

CSR-ATTESTATION-2023.asn, draft-ietf-lamps-csr-attestation.md
@hannestschofenig , @thomas-fossati please review.
Closes #70
=> Added a hint to the RP. Closes #70

CSR-ATTESTATION-2023.asn, draft-ietf-lamps-csr-attestation.md
Addresses issue https://github.com/lamps-wg/csr-attestation/issues/82
=> Re-defining the Evidence Hint

draft-ietf-lamps-csr-attestation.md
=> typo on MCR name

draft-ietf-lamps-csr-attestation.md
Otherwise the ref to DICE is not resolved
=> fix table rendering

draft-ietf-lamps-csr-attestation.md
Small surgery on the initial contents of the Attestation Evidence OID Registry
Fix #96
=> Attestation Evidence OID Registry small surgery

draft-ietf-lamps-csr-attestation.md
=> Consitent use of certification path

draft-ietf-lamps-csr-attestation.md
Also fixed Monty's ASN.1 in the TPM example section.
=> Added an appendix showing how to use EvidenceStatementSet

CSR-ATTESTATION-WITH-DiceTcbInfo.txt, draft-ietf-lamps-csr-attestation.md
PR to add DiceTcbInfo example to main
=> Dice tcb info example

draft-ietf-lamps-csr-attestation.md
I don't know why we are now starting to track the changes from draft to draft version.
=> Removing change history

draft-ietf-lamps-csr-attestation.md
=> Addressing MSJ comments

draft-ietf-lamps-csr-attestation.md
Aiming to address the mailing list discussion
Question: Is there a good ASN.1 structure to use for FQDNs?
=> New Hint Text Proposal

draft-ietf-lamps-csr-attestation.md
Update references to TCG OID Registry
Update TCG OID descriptions to match TCG OID Registry
=> Update TCG OIDs and Registry

draft-ietf-lamps-csr-attestation.md
Reverts lamps-wg/csr-attestation#162
=> Revert "Update TCG OIDs and Registry"

CSR-ATTESTATION-2025.asn, draft-ietf-lamps-csr-attestation.md
=> fixed id-aa-ar

draft-ietf-lamps-csr-attestation.md
=> Addressed Mike StJohns comments

draft-ietf-lamps-csr-attestation.md
In response to https://github.com/lamps-wg/csr-attestation/issues/188
=> Adding information about AttestationResultBundle Processing

draft-ietf-lamps-csr-attestation.md, tpm-appdx.md.donotbuild
=> Removed the TPM appendix
